name: cd

on:
    workflow_run:
        workflows: ["ci"]
        types:
            - completed

jobs:
    start:
        runs-on: be-socialapp

        steps:
            # - name: chạy lần đầu
            #   run: sudo docker compose up -d
            - name: Cleanup Docker
              run: sudo docker system prune -af --volumes || true
              
            - name: Kéo image mới về
              run: sudo docker compose pull BE

            - name: Tạo lại container BE
              run: sudo docker compose up -d --no-deps --force-recreate BE